apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  type: NodePort
  selector:
    app: employee-service
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # Access via <minikube-ip>:30090
