server:
  port: 9082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: employee-service
  main:
    allow-bean-definition-overriding: false

# Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3

# Database configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/employee_service_db
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hikari Configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update  # or 'validate' or 'create' or 'create-drop' depending on your need
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# Topic configuration
kafka:
  topic:
    employee: employee-topic
