server:
  port: 9090

spring:
  application:
    name: employee-service
  main:
    allow-bean-definition-overriding: false

# Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/employee_service_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hikari Configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

# JPA configuration
  jpa:
    hibernate:
      ddl-auto: update  # or 'validate' or 'create' or 'create-drop' depending on your need
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# SonarQube configuration
sonar:
  enabled: true
  host:
    url: http://localhost:9000
  projectKey: employee-service
  projectName: employee-service
  login: squ_51678fa10c9b81df956ee9ec9eb994e59ae38255
  sources: src/main/java
  tests: src/test/java
  java:
    binaries: build/classes
  sourceEncoding: UTF-8

