server:
  port: 9082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: employee-service
  main:
    allow-bean-definition-overriding: false
  config:
    import: "configserver:http://localhost:8888"
  profiles:
    active: dev  # Set the active profile to 'dev' for development environment

