spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql-prod}:3306/employee_service_db

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
